apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nexus-snyk-security-plugin
  annotations:
    github.com/project-slug: snyk/nexus-snyk-security-plugin
    github.com/team-slug: snyk/cli
spec:
  type: supply-chain-tooling
  lifecycle: "-"
  owner: cli
